/*
 * This file is generated by jOOQ.
 */
package com.home.jooq.db.autocreated;


import com.home.jooq.db.autocreated.tables.Author;
import com.home.jooq.db.autocreated.tables.AuthorBookCrs;
import com.home.jooq.db.autocreated.tables.Book;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -10730807;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Таблица авторов
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * Кросс таблица: авторы-книги
     */
    public final AuthorBookCrs AUTHOR_BOOK_CRS = AuthorBookCrs.AUTHOR_BOOK_CRS;

    /**
     * Таблица книг
     */
    public final Book BOOK = Book.BOOK;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.AUTHOR_BOOK_CRS_SEQ,
            Sequences.AUTHOR_SEQ,
            Sequences.BOOK_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            AuthorBookCrs.AUTHOR_BOOK_CRS,
            Book.BOOK);
    }
}
