/*
 * This file is generated by jOOQ.
 */
package com.home.jooq.db.autocreated;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.author_book_crs_seq</code>
     */
    public static final Sequence<Long> AUTHOR_BOOK_CRS_SEQ = Internal.createSequence("author_book_crs_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), 101, null, null, null, false, null);

    /**
     * The sequence <code>public.author_seq</code>
     */
    public static final Sequence<Long> AUTHOR_SEQ = Internal.createSequence("author_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), 101, null, null, null, false, null);

    /**
     * The sequence <code>public.book_seq</code>
     */
    public static final Sequence<Long> BOOK_SEQ = Internal.createSequence("book_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false), 101, null, null, null, false, null);
}
